# Generated by Django 4.1.4 on 2023-01-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0003_apoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoint',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
