# Generated by Django 4.1.4 on 2023-01-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0004_alter_apoint_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('card_holder_name', models.CharField(max_length=200)),
            ],
        ),
    ]
