# Generated by Django 4.1.4 on 2023-01-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0005_paymentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='services_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=25)),
                ('test_desc', models.CharField(max_length=100)),
                ('test_price', models.IntegerField()),
                ('test_image', models.FileField(upload_to='labapp/static/non_veg')),
            ],
        ),
    ]
