# Generated by Django 4.1.4 on 2023-01-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0006_services_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_model',
            name='test_image',
            field=models.FileField(upload_to='labapp/static/'),
        ),
    ]
