# Generated by Django 4.1.4 on 2023-01-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0008_delete_apoint_delete_paymentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='apoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='paymentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('card_holder_name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
