# Generated by Django 4.1.4 on 2023-01-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0009_apoint_paymentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentmodel',
        ),
    ]
