# Generated by Django 4.1.4 on 2023-01-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0011_paymentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
