# Generated by Django 4.1.4 on 2023-01-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0012_alter_paymentmodel_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='card_holder_name',
        ),
    ]
